[build]
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Password protection
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[context.production]
  environment = { ACCESS_TOKEN = "ARKAS2024DEMO" } 